In [1]:
import numpy as np

In [2]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
a = np.array([[0, 2, 3], [4, 5, 6, 7]])
a

array([list([0, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [4]:
a = np.array([[0, "John", 2, 3], [4, 5, 6, 7]])
a

array([['0', 'John', '2', '3'],
       ['4', '5', '6', '7']], dtype='<U11')

In [5]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
a.shape

(2, 4)

In [7]:
a[1,3]

7

In [8]:
a[1,2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [9]:
a[0]

array([0, 1, 2, 3])

In [10]:
a[1]

array([4, 5, 8, 7])

In [11]:
b = np.array([3,5])

In [12]:
b

array([3, 5])