## Monte Carlo - Forecasting Stock Prices - Part II 

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Forecasting Future Stock Prices – continued:

In [1]:
import numpy as np  
import pandas as pd  
from pandas_datareader import data as wb  
import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

ticker = 'MSFT' 
data = pd.DataFrame()
data[ticker] = wb.DataReader(ticker, data_source='morningstar', start='2002-1-1')['Close']

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [2]:
type(drift)

pandas.core.series.Series

In [3]:
drift.values

array([0.00011501])

In [4]:
type(stdev)

pandas.core.series.Series

In [5]:
stdev.values

array([0.01688708])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [6]:
t_intervals = 250
iterations = 10

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 
<br \>
$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [7]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))
daily_returns

array([[0.99724898, 1.02631366, 0.95151146, ..., 0.9705615 , 1.02218199,
        1.00359063],
       [1.01374309, 0.99325944, 0.98399011, ..., 1.01478026, 0.9886481 ,
        0.97549046],
       [0.99862795, 0.98674575, 1.00023035, ..., 0.9731904 , 1.01098334,
        0.99382116],
       ...,
       [1.0277222 , 1.00919623, 0.98525741, ..., 1.00387919, 1.02601766,
        1.02063607],
       [1.01832682, 0.98865206, 1.01221144, ..., 1.01019662, 1.02786892,
        0.98813867],
       [1.01642936, 0.99301843, 0.96960162, ..., 1.00440218, 0.99784049,
        1.0283069 ]])