## Monte Carlo - Forecasting Stock Prices - Part II 

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Forecasting Future Stock Prices – continued:

In [1]:
import numpy as np  
import pandas as pd  
from pandas_datareader import data as wb  
import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

ticker = 'MSFT' 
data = pd.DataFrame()
data[ticker] = wb.DataReader(ticker, data_source='yahoo', start='2000-1-1')['Adj Close']

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [2]:
type(drift)

pandas.core.series.Series

In [3]:
drift.values

array([  7.46364383e-06])

In [4]:
type(stdev)

pandas.core.series.Series

In [5]:
stdev.values

array([ 0.01930022])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [6]:
t_intervals = 250
iterations = 10

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 
<br \>
$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [7]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))
daily_returns

array([[ 1.02075661,  1.02073224,  1.01460416, ...,  1.01724425,
         1.01269655,  0.99071876],
       [ 1.0025275 ,  0.97974751,  1.01559335, ...,  0.99999806,
         1.00583085,  1.02554143],
       [ 1.00580422,  0.99780802,  0.98305669, ...,  1.01328651,
         1.02262953,  0.98788894],
       ..., 
       [ 0.96002206,  1.01053117,  0.98712622, ...,  1.0316798 ,
         0.97316948,  1.00184806],
       [ 0.98687198,  1.01823717,  1.03000581, ...,  0.97372727,
         0.98848068,  0.9741575 ],
       [ 1.01368025,  0.99850808,  1.01223003, ...,  1.02065024,
         1.02702303,  0.99800838]])