## Monte Carlo - Forecasting Stock Prices - Part II 

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Forecasting Future Stock Prices – continued:

In [1]:
import numpy as np  
import pandas as pd  
from pandas_datareader import data as wb  
import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

ticker = 'MSFT' 
data = pd.DataFrame()
data[ticker] = wb.DataReader(ticker, data_source='iex', start='2015-1-1')['close']

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

5y


******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [2]:
type(drift)

pandas.core.series.Series

In [3]:
drift.values

array([0.00086773])

In [4]:
type(stdev)

pandas.core.series.Series

In [5]:
stdev.values

array([0.01458333])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [6]:
t_intervals = 250
iterations = 10

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 
<br \>
$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [7]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))
daily_returns

array([[1.01095699, 0.9769792 , 0.99202127, ..., 0.9886795 , 0.99794908,
        0.97714619],
       [1.01842063, 1.00408016, 1.00199587, ..., 0.97127252, 1.0149269 ,
        1.00687163],
       [0.98575652, 1.01999794, 1.00000545, ..., 0.99449251, 1.01975812,
        1.01872293],
       ...,
       [1.00375482, 0.99546051, 1.00401341, ..., 1.01439301, 1.01589728,
        0.98207802],
       [0.98553824, 0.98907875, 1.0176363 , ..., 1.00112249, 0.98386497,
        0.99711455],
       [0.98769115, 1.01029332, 0.99612666, ..., 0.98857682, 0.99242259,
        0.9834048 ]])